### ISSUE TITLE
Missing passport from package.json

### ISSUE THREAD

**Issue by dvalentiate** [jasnell/lambda#1]
Missing `passport` dependency in `package.json`.

When trying to do `docker build -t lambda-example .` I got the following:

```
npm info it worked if it ends with ok
npm info using npm@3.3.6
npm info using node@v5.0.0
npm info lifecycle lambda-daemon@0.0.2~prestart: lambda-daemon@0.0.2
npm info lifecycle lambda-daemon@0.0.2~start: lambda-daemon@0.0.2

> lambda-daemon@0.0.2 start /usr/src/app
> node lib/lambdad.js

module.js:339
    throw err;
    ^

Error: Cannot find module 'passport'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/src/app/lib/lambdad.js:15:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)

npm info lifecycle lambda-daemon@0.0.2~start: Failed to exec start script
npm ERR! Linux 4.1.10-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! lambda-daemon@0.0.2 start: `node lib/lambdad.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lambda-daemon@0.0.2 start script 'node lib/lambdad.js'.
npm ERR! This is most likely a problem with the lambda-daemon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/lambdad.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lambda-daemon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by jasnell** [comment]
I need to get this updated and cleaned up a bit more but haven't had the time. I'll see if I can get things updated early next week.

**Comment by dvalentiate** [comment]
After giving this project a spin I realized that I needed more a server that could support multiple lambdas at the same time.

So I created it https://www.npmjs.com/package/dev-lambda .

Thanks for the inspiration, particularly on using docker with node.

**Comment by jasnell** [comment]
@dvalentiate ... very happy that you were able to get inspiration from this :-)

**Comment by thond1st** [comment]
I just added `"passport": "*"` into daemon/package.json and it worked even with the latest/current version of passport.
